project: dragon-board
snaps:
  kernel: dragonboard-kernel
  os: ubuntu-core
  gadget: dragonboard
configs:
  arch: arm64
  baseimage: base.img
  recoverytype: recovery
  recoverysize: 768
  release: 16
  channel: edge
  size: 4
  packages:
    - snapweb
  partition-type: gpt
  bootloader: u-boot
udf:
  binary: ./ubuntu-device-flash
  command: core
debug:
  devmode: on
  ssh: on
  xz: off
recovery:
  type: factory_install
  filesystem-label: ESP
  boot-partition:
  systemboot-partition:
  writable-partition:
  boot-image:
  systemboot-image:
  writable-image:
  sign-serial: on
  sign-api-key: U2VyaWFsIFZhdWx0Cg
